### ---------- User Authentication ----------- ###
### Register ###
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "user1_password"
}

### Login ###
# @name postLogin
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email": "user1@example.com",
    "password": "user1_password"
}

### Token
@token = {{ postLogin.response.body.token }}

### ---------- Instrumentations ----------- ###
### Retrieve instrumentations tree ###
GET http://localhost:8080/api/instrumentations?query=Violi    
Content-Type: application/json
Authorization: Bearer {{token}}

### ---------- Catalog Composers ----------- ###
### Retrieve catalog composers by name ###
# @name getComposerByName
GET http://localhost:8080/api/catalog-composers?name=Pachebel    
Content-Type: application/json
Authorization: Bearer {{token}}

### ---------- Catalog Works ----------- ###
### Retrieve catalog works by composer ###
# @name getWorksBySearch
GET http://localhost:8080/api/catalog-works?composerId={{getComposerByName.response.body.content[0].id}}&query=Canon&instrumentationIds=
Content-Type: application/json
Authorization: Bearer {{token}}

### Get catalog work by ID ###
GET http://localhost:8080/api/catalog-works/{{getWorksBySearch.response.body.content[0].id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### ---------- User Works ----------- ###
### Create user work from catalog work  with composerId ###
POST http://localhost:8080/api/works
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "{{getWorksBySearch.response.body.content[0].title}}",
    "classification": "My custom classification",
    "notes": "Excited to learn this piece!",
    "composerId": "{{getWorksBySearch.response.body.content[0].composer.id}}",
    "difficulty": "BEGINNER",
    "status": "LEARNING",
    "techniqueIds": [],
    "instrumentation": [
        {
            "id": "{{getWorksBySearch.response.body.content[0].settings[0].slots[0].alternatives[0].id}}"
        }
    ]
}   

### Create user work from catalog work with composerName ###
POST http://localhost:8080/api/works
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "{{getWorksBySearch.response.body.content[0].title}}",
    "classification": "{{getWorksBySearch.response.body.content[0].classification}}",
    "notes": "Excited to learn this piece!",
    "composerName": "Gupegto",
    "difficulty": "ADVANCED",
    "status": "PLANNED",
    "techniqueIds": [],
    "instrumentation": [
        {
            "id": "{{getWorksBySearch.response.body.content[0].settings[0].slots[0].alternatives[0].id}}"
        }
    ]
}   


### Get user works ###
# @name getUserWorks
GET http://localhost:8080/api/works
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user works by difficulty & status ###
GET http://localhost:8080/api/works?difficulty=BEGINNER&status=LEARNING
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user work by ID ###
# @name getUserWorkById
GET http://localhost:8080/api/works/{{getUserWorks.response.body.content[0].id}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Update user work by ID ###
PUT http://localhost:8080/api/works/{{getUserWorkById.response.body.id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Updated title",
    "classification": "Updated classification",
    "notes": "Updated notes for this piece",
    "status": "READY"
}

### Delete user work by ID ###
DELETE http://localhost:8080/api/works/{{getUserWorks.response.body.content[0].id}}
Content-Type: application/json
Authorization: Bearer {{token}}
