INSERT INTO instrumentation (name, category_id) VALUES
-- General
('Any Instrument', (SELECT id FROM categories WHERE name = 'General')),
('Basso Continuo', (SELECT id FROM categories WHERE name = 'General')),
('Ethnic Instrument', (SELECT id FROM categories WHERE name = 'General')),
('Melody Instrument', (SELECT id FROM categories WHERE name = 'General')),
('Solo Instrument', (SELECT id FROM categories WHERE name = 'General')),
('Soloist', (SELECT id FROM categories WHERE name = 'General')),
('Treble Instrument', (SELECT id FROM categories WHERE name = 'General')),
('Wind Instrument', (SELECT id FROM categories WHERE name = 'General')),

-- Strings
('Arpeggione', (SELECT id FROM categories WHERE name = 'Strings')),
('Balalaika', (SELECT id FROM categories WHERE name = 'Strings')),
('Baryton', (SELECT id FROM categories WHERE name = 'Strings')),
('Bass Guitar', (SELECT id FROM categories WHERE name = 'Strings')),
('Bass Viol', (SELECT id FROM categories WHERE name = 'Strings')),
('Calchedon', (SELECT id FROM categories WHERE name = 'Strings')),
('Cello', (SELECT id FROM categories WHERE name = 'Strings')),
('Chittarone', (SELECT id FROM categories WHERE name = 'Strings')),
('Domra', (SELECT id FROM categories WHERE name = 'Strings')),
('Double Bass', (SELECT id FROM categories WHERE name = 'Strings')),
('Guitar', (SELECT id FROM categories WHERE name = 'Strings')),
('Harp', (SELECT id FROM categories WHERE name = 'Strings')),
('Harpolyre', (SELECT id FROM categories WHERE name = 'Strings')),
('Lute', (SELECT id FROM categories WHERE name = 'Strings')),
('Mandola', (SELECT id FROM categories WHERE name = 'Strings')),
('Mandolin', (SELECT id FROM categories WHERE name = 'Strings')),
('Orpharion', (SELECT id FROM categories WHERE name = 'Strings')),
('Theorbo', (SELECT id FROM categories WHERE name = 'Strings')),
('Viol', (SELECT id FROM categories WHERE name = 'Strings')),
('Viola', (SELECT id FROM categories WHERE name = 'Strings')),
('Viola d''amore', (SELECT id FROM categories WHERE name = 'Strings')),
('Viola da gamba', (SELECT id FROM categories WHERE name = 'Strings')),
('Violin', (SELECT id FROM categories WHERE name = 'Strings')),
('Violino Piccolo', (SELECT id FROM categories WHERE name = 'Strings')),
('Violone', (SELECT id FROM categories WHERE name = 'Strings')),
('Zither', (SELECT id FROM categories WHERE name = 'Strings')),

-- Woodwinds
('Accordion', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Alto Flute', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Alto Saxophone', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Bandoneon', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Baritone Saxophone', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Basset Horn', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Bass Clarinet', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Bass Flute', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Bass Recorder', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Bassoon', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Bombarde', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Chalumeau', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Clarinet', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Contrabassoon', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('English Horn', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Flute', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Harmonica', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Heckelphone', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Oboe', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Oboe d''amore', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Piccolo', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Pipe', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Recorder', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Saxophone', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Soprano Saxophone', (SELECT id FROM categories WHERE name = 'Woodwinds')),
('Tenor Saxophone', (SELECT id FROM categories WHERE name = 'Woodwinds')),

-- Brass
('Alto Horn', (SELECT id FROM categories WHERE name = 'Brass')),
('Cornet', (SELECT id FROM categories WHERE name = 'Brass')),
('Cornett', (SELECT id FROM categories WHERE name = 'Brass')),
('Euphonium', (SELECT id FROM categories WHERE name = 'Brass')),
('Horn', (SELECT id FROM categories WHERE name = 'Brass')),
('Piccolo Trumpet', (SELECT id FROM categories WHERE name = 'Brass')),
('Serpent', (SELECT id FROM categories WHERE name = 'Brass')),
('Trombone', (SELECT id FROM categories WHERE name = 'Brass')),
('Trumpet', (SELECT id FROM categories WHERE name = 'Brass')),
('Tuba', (SELECT id FROM categories WHERE name = 'Brass')),

-- Keyboard
('Bayan', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Celesta', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Clavichord', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Color Organ', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Electric Organ', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Electric Piano', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Harmonium', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Harpsichord', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Keyboard', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Lira Organizzata', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Organ', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Piano', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Pianola', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Player Piano', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Prepared Piano', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Spinet', (SELECT id FROM categories WHERE name = 'Keyboard')),
('Toy Piano', (SELECT id FROM categories WHERE name = 'Keyboard')),

-- Vocal
('Alto', (SELECT id FROM categories WHERE name = 'Vocal')),
('Baritone', (SELECT id FROM categories WHERE name = 'Vocal')),
('Bass', (SELECT id FROM categories WHERE name = 'Vocal')),
('Boy Soprano', (SELECT id FROM categories WHERE name = 'Vocal')),
('Contralto', (SELECT id FROM categories WHERE name = 'Vocal')),
('Countertenor', (SELECT id FROM categories WHERE name = 'Vocal')),
('High Voice', (SELECT id FROM categories WHERE name = 'Vocal')),
('Mezzo-Soprano', (SELECT id FROM categories WHERE name = 'Vocal')),
('Narrator', (SELECT id FROM categories WHERE name = 'Vocal')),
('Soprano', (SELECT id FROM categories WHERE name = 'Vocal')),
('Speaker', (SELECT id FROM categories WHERE name = 'Vocal')),
('Tenor', (SELECT id FROM categories WHERE name = 'Vocal')),
('Treble', (SELECT id FROM categories WHERE name = 'Vocal')),
('Voice', (SELECT id FROM categories WHERE name = 'Vocal')),

-- Percussion
('Bell', (SELECT id FROM categories WHERE name = 'Percussion')),
('Carillon', (SELECT id FROM categories WHERE name = 'Percussion')),
('Castanet', (SELECT id FROM categories WHERE name = 'Percussion')),
('Cimbalom', (SELECT id FROM categories WHERE name = 'Percussion')),
('Claves', (SELECT id FROM categories WHERE name = 'Percussion')),
('Cymbal', (SELECT id FROM categories WHERE name = 'Percussion')),
('Drum', (SELECT id FROM categories WHERE name = 'Percussion')),
('Drum Kit', (SELECT id FROM categories WHERE name = 'Percussion')),
('Glockenspiel', (SELECT id FROM categories WHERE name = 'Percussion')),
('Gong', (SELECT id FROM categories WHERE name = 'Percussion')),
('Handclaps', (SELECT id FROM categories WHERE name = 'Percussion')),
('Maracas', (SELECT id FROM categories WHERE name = 'Percussion')),
('Marimba', (SELECT id FROM categories WHERE name = 'Percussion')),
('Percussion', (SELECT id FROM categories WHERE name = 'Percussion')),
('Snare Drum', (SELECT id FROM categories WHERE name = 'Percussion')),
('Timpani', (SELECT id FROM categories WHERE name = 'Percussion')),
('Triangle', (SELECT id FROM categories WHERE name = 'Percussion')),
('Tubular Bells', (SELECT id FROM categories WHERE name = 'Percussion')),
('Vibraphone', (SELECT id FROM categories WHERE name = 'Percussion')),
('Woodblock', (SELECT id FROM categories WHERE name = 'Percussion')),
('Xylorimba', (SELECT id FROM categories WHERE name = 'Percussion')),
('Zoomoozophone', (SELECT id FROM categories WHERE name = 'Percussion')),

-- Electronic
('Amplified Flute', (SELECT id FROM categories WHERE name = 'Electronic')),
('Amplified Piano', (SELECT id FROM categories WHERE name = 'Electronic')),
('Amplified Plant', (SELECT id FROM categories WHERE name = 'Electronic')),
('Digital Sampler', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electric Bell', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electric Cello', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electric Double Bass', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electric Flute', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electric Guitar', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electric Viola', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electric Violin', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electronic Tape', (SELECT id FROM categories WHERE name = 'Electronic')),
('Electronics', (SELECT id FROM categories WHERE name = 'Electronic')),
('Live Electronics', (SELECT id FROM categories WHERE name = 'Electronic')),
('Microphone', (SELECT id FROM categories WHERE name = 'Electronic')),
('Ondes Martenot', (SELECT id FROM categories WHERE name = 'Electronic')),
('Shortwave Receiver', (SELECT id FROM categories WHERE name = 'Electronic')),
('Synthesized Tape', (SELECT id FROM categories WHERE name = 'Electronic')),
('Synthesizer', (SELECT id FROM categories WHERE name = 'Electronic')),
('Theremin', (SELECT id FROM categories WHERE name = 'Electronic')),
('Turntable', (SELECT id FROM categories WHERE name = 'Electronic')),

-- Ensemble
('Baroque Orchestra', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Brass Band', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Brass Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Brass Quintet', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Chamber Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Chamber Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Chamber Orchestra', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Children''s Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Concertino', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Double Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Female Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Gagaku Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Gamelan Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Instrumental Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Jazz Band', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Jazz Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Male Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Military Band', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Mixed Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Mixed Consort', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Orchestra', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Percussion Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Piano Quartet', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Rock Band', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Saxophone Quartet', (SELECT id FROM categories WHERE name = 'Ensemble')),
('String Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('String Orchestra', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Symphony Orchestra', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Treble Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Unison Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Viol Consort', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Viol Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Vocal Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Wind Ensemble', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Wind Quintet', (SELECT id FROM categories WHERE name = 'Ensemble')),
('Women''s Chorus', (SELECT id FROM categories WHERE name = 'Ensemble')),

-- Mechanical
('Clock Organ', (SELECT id FROM categories WHERE name = 'Mechanical')),
('Flute-Clock', (SELECT id FROM categories WHERE name = 'Mechanical')),
('Mechanical Clock', (SELECT id FROM categories WHERE name = 'Mechanical')),
('Music Box', (SELECT id FROM categories WHERE name = 'Mechanical')),

-- Traditional
('Biwa', (SELECT id FROM categories WHERE name = 'Traditional')),
('Koto', (SELECT id FROM categories WHERE name = 'Traditional')),
('Shakuhachi', (SELECT id FROM categories WHERE name = 'Traditional')),
('Sho', (SELECT id FROM categories WHERE name = 'Traditional')),

-- Other
('Airplane Propeller', (SELECT id FROM categories WHERE name = 'Other')),
('Assistant', (SELECT id FROM categories WHERE name = 'Other')),
('Conch Shell', (SELECT id FROM categories WHERE name = 'Other')),
('Glass Harmonica', (SELECT id FROM categories WHERE name = 'Other')),
('Helicopter', (SELECT id FROM categories WHERE name = 'Other'))
ON CONFLICT (name) DO NOTHING;